/**
 * Generated by scripts/build-dictionaries.mjs — do not edit by hand.
 *
 * Side-effect free: exports data only. Nothing is registered in a global
 * registry, which is what lets `sideEffects: false` prune unused dictionaries
 * instead of silently dropping them at runtime.
 */

/*
 * Minimum inter-code Hamming distance (tau) = 5, computed offline over all
 * four relative rotations, after dropping codes find() can never reach.
 * Correctable radius floor((tau-1)/2) = 2.
 */

/** @type {import('../dictionary.js').DictionaryDefinition} */
export default {
  name: "APRILTAG_16h5",
  nBits: 16,
  tau: 5,
  maxCorrectionBits: 2,
  codeList: [8987,11941,13418,17849,31142,32619,45912,59205,65113,5485,14347,61611,3460,18230,35954,44816,2364,37812,42243,18063,57655,22421,57154,7197,59868,29613,44383,54576,1994,44846],
};
