/**
 * Generated by scripts/build-dictionaries.mjs — do not edit by hand.
 *
 * Side-effect free: exports data only. Nothing is registered in a global
 * registry, which is what lets `sideEffects: false` prune unused dictionaries
 * instead of silently dropping them at runtime.
 */

/*
 * Minimum inter-code Hamming distance (tau) = 9, computed offline.
 * Correctable radius floor((tau-1)/2) = 4.
 */

/** @type {import('../dictionary.js').DictionaryDefinition} */
export default {
  name: "APRILTAG_25h9",
  nBits: 25,
  tau: 9,
  maxCorrectionBits: 4,
  codeList: [22399985,31773110,24841064,32164301,19797198,3492027,7821286,17194411,29008615,14591624,8509735,5354049,14403758,31788569,22550994,23954050,23322677,10328961,24374980,11418121,6257745,27342844,14456162,25177669,29578284,8851364,9520905,23495920,13169317,8601275,5861759,20762704,16386769,28795824,12161486],
};
