/**
 * Generated by scripts/build-dictionaries.mjs — do not edit by hand.
 *
 * Side-effect free: exports data only. Nothing is registered in a global
 * registry, which is what lets `sideEffects: false` prune unused dictionaries
 * instead of silently dropping them at runtime.
 */

/*
 * OpenCV DICT_4X4_50: first 50 codes of the 4x4 set.
 * Minimum inter-code Hamming distance (tau) = 4.
 * Correctable radius floor((tau-1)/2) = 1; OpenCV declares maxCorrectionBits = 1.
 */

/** @type {import('../dictionary.js').DictionaryDefinition} */
export default {
  name: "DICT_4X4_50",
  nBits: 16,
  tau: 4,
  maxCorrectionBits: 1,
  codeList: [[181,50],[15,154],[51,45],[153,70],[84,158],[121,205],[158,46],[196,242],[254,218],[207,86],[249,145],[17,167],[14,183],[42,15],[36,177],[38,62],[70,101],[102,0],[108,94],[118,175],[134,139],[176,43],[204,213],[221,130],[254,71],[148,113],[172,228],[165,84],[33,35],[52,111],[68,21],[87,178],[158,207],[240,203],[8,174],[9,41],[24,117],[4,255],[13,246],[28,90],[23,24],[42,40],[50,140],[56,178],[36,232],[46,235],[45,63],[75,100],[80,46],[80,19]],
};
