/**
 * Generated by scripts/build-dictionaries.mjs — do not edit by hand.
 *
 * Side-effect free: exports data only. Nothing is registered in a global
 * registry, which is what lets `sideEffects: false` prune unused dictionaries
 * instead of silently dropping them at runtime.
 */

/*
 * OpenCV DICT_5X5_50: first 50 codes of the 5x5 set.
 * Minimum inter-code Hamming distance (tau) = 8.
 * Correctable radius floor((tau-1)/2) = 3; OpenCV declares maxCorrectionBits = 3.
 */

/** @type {import('../dictionary.js').DictionaryDefinition} */
export default {
  name: "DICT_5X5_50",
  nBits: 25,
  tau: 8,
  maxCorrectionBits: 3,
  codeList: [[162,217,94,0],[14,3,115,0],[215,135,110,1],[129,202,251,1],[215,90,146,0],[234,4,22,1],[105,235,246,0],[113,10,53,1],[134,176,153,0],[152,159,210,1],[158,119,1,1],[209,109,96,0],[243,21,136,1],[47,56,179,0],[254,126,84,0],[40,241,191,1],[75,211,172,0],[95,81,55,1],[123,38,226,0],[131,14,244,0],[150,237,58,1],[168,114,32,0],[181,134,80,1],[93,9,111,0],[206,104,17,1],[210,204,185,0],[225,231,69,1],[17,33,35,0],[29,203,57,0],[18,17,29,1],[19,155,183,0],[27,68,57,1],[32,104,103,0],[37,85,100,0],[35,33,221,0],[61,55,245,0],[76,197,86,0],[65,104,128,1],[77,86,142,1],[67,30,57,0],[86,148,18,1],[82,151,207,0],[108,36,251,1],[97,132,236,1],[109,63,24,1],[116,177,61,0],[116,220,203,1],[124,164,3,0],[122,200,146,1],[123,91,235,1]],
};
