/**
 * Generated by scripts/build-dictionaries.mjs — do not edit by hand.
 *
 * Side-effect free: exports data only. Nothing is registered in a global
 * registry, which is what lets `sideEffects: false` prune unused dictionaries
 * instead of silently dropping them at runtime.
 */

/** Every dictionary bundled with this package. */
export const DICTIONARY_NAMES = /** @type {const} */ ([
  "APRILTAG_16h5",
  "APRILTAG_25h7",
  "APRILTAG_25h9",
  "APRILTAG_36h10",
  "APRILTAG_36h11",
  "APRILTAG_36h9",
  "ARTAG",
  "ARTOOLKITPLUS",
  "ARTOOLKITPLUSBCH",
  "ARUCO",
  "ARUCO_DEFAULT",
  "ARUCO_DEFAULT_OPENCV",
  "ARUCO_MIP_16h3",
  "ARUCO_MIP_25h7",
  "ARUCO_MIP_36h12",
  "CHILITAGS",
  "DICT_4X4_100",
  "DICT_4X4_1000",
  "DICT_4X4_250",
  "DICT_4X4_50",
  "DICT_5X5_100",
  "DICT_5X5_1000",
  "DICT_5X5_250",
  "DICT_5X5_50",
  "DICT_6X6_100",
  "DICT_6X6_1000",
  "DICT_6X6_250",
  "DICT_6X6_50",
  "DICT_7X7_100",
  "DICT_7X7_1000",
  "DICT_7X7_250",
  "DICT_7X7_50",
]);

/** Aliases kept for pre-3.0 compatibility. */
export const DICTIONARY_ALIASES = {
  ARUCO_4X4_1000: 'DICT_4X4_1000',
  ARUCO_5X5_1000: 'DICT_5X5_1000',
  ARUCO_6X6_1000: 'DICT_6X6_1000',
  ARUCO_7X7_1000: 'DICT_7X7_1000',
};

const loaders = {
  "APRILTAG_16h5": () => import("./apriltag-16h5.js"),
  "APRILTAG_25h7": () => import("./apriltag-25h7.js"),
  "APRILTAG_25h9": () => import("./apriltag-25h9.js"),
  "APRILTAG_36h10": () => import("./apriltag-36h10.js"),
  "APRILTAG_36h11": () => import("./apriltag-36h11.js"),
  "APRILTAG_36h9": () => import("./apriltag-36h9.js"),
  "ARTAG": () => import("./artag.js"),
  "ARTOOLKITPLUS": () => import("./artoolkitplus.js"),
  "ARTOOLKITPLUSBCH": () => import("./artoolkitplusbch.js"),
  "ARUCO": () => import("./aruco.js"),
  "ARUCO_DEFAULT": () => import("./aruco-default.js"),
  "ARUCO_DEFAULT_OPENCV": () => import("./aruco-default-opencv.js"),
  "ARUCO_MIP_16h3": () => import("./aruco-mip-16h3.js"),
  "ARUCO_MIP_25h7": () => import("./aruco-mip-25h7.js"),
  "ARUCO_MIP_36h12": () => import("./aruco-mip-36h12.js"),
  "CHILITAGS": () => import("./chilitags.js"),
  "DICT_4X4_100": () => import("./dict-4x4-100.js"),
  "DICT_4X4_1000": () => import("./dict-4x4-1000.js"),
  "DICT_4X4_250": () => import("./dict-4x4-250.js"),
  "DICT_4X4_50": () => import("./dict-4x4-50.js"),
  "DICT_5X5_100": () => import("./dict-5x5-100.js"),
  "DICT_5X5_1000": () => import("./dict-5x5-1000.js"),
  "DICT_5X5_250": () => import("./dict-5x5-250.js"),
  "DICT_5X5_50": () => import("./dict-5x5-50.js"),
  "DICT_6X6_100": () => import("./dict-6x6-100.js"),
  "DICT_6X6_1000": () => import("./dict-6x6-1000.js"),
  "DICT_6X6_250": () => import("./dict-6x6-250.js"),
  "DICT_6X6_50": () => import("./dict-6x6-50.js"),
  "DICT_7X7_100": () => import("./dict-7x7-100.js"),
  "DICT_7X7_1000": () => import("./dict-7x7-1000.js"),
  "DICT_7X7_250": () => import("./dict-7x7-250.js"),
  "DICT_7X7_50": () => import("./dict-7x7-50.js"),
};

const cache = new Map();

/**
 * Load a bundled dictionary definition by name. Dynamic import, so a bundler
 * code-splits each dictionary rather than putting all of them in your
 * initial chunk. Import the data module directly for a static dependency.
 *
 * @param {string} name
 * @returns {Promise<import('../dictionary.js').DictionaryDefinition>}
 */
export async function loadDictionaryDefinition(name) {
  const key = DICTIONARY_ALIASES[name] || name;
  if (cache.has(key)) return cache.get(key);
  const load = loaders[key];
  if (!load) {
    const { UnknownDictionaryError } = await import('../errors.js');
    throw new UnknownDictionaryError(name, DICTIONARY_NAMES.slice());
  }
  const mod = await load();
  cache.set(key, mod.default);
  return mod.default;
}

/**
 * Load a dictionary by name, already constructed and cached.
 * @param {string} name
 * @returns {Promise<import('../dictionary.js').Dictionary>}
 */
const instances = new Map();

export async function loadDictionary(name) {
  const key = DICTIONARY_ALIASES[name] || name;
  if (instances.has(key)) return instances.get(key);
  const def = await loadDictionaryDefinition(name);
  const { Dictionary } = await import('../dictionary.js');
  const dict = new Dictionary(def);
  instances.set(key, dict);
  return dict;
}
